# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminHandleLog',
            fields=[
                ('admin_hadle_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('handle_time', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'admin_handle_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('leader_id', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=128)),
                ('last_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('sex', models.IntegerField(default=1)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phone_num', models.CharField(max_length=11)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'admin_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminLoginLog',
            fields=[
                ('admin_login_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('login_ip', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'admin_login_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminPower',
            fields=[
                ('admin_power_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'admin_power',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('admin_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'admin_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AmountOfMaterial',
            fields=[
                ('amount_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('amount_of_use', models.IntegerField()),
            ],
            options={
                'db_table': 'amount_of_material',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpHandleLog',
            fields=[
                ('emp_handle_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('handle_time', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'emp_handle_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpInfo',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('emp_no', models.CharField(blank=True, max_length=64, null=True)),
                ('sex', models.IntegerField(default=1)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('join_time', models.DateTimeField(blank=True, null=True)),
                ('work_status', models.CharField(blank=True, max_length=32, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('subsidy', models.IntegerField(blank=True, null=True)),
                ('work_time', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'emp_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpLoginLog',
            fields=[
                ('emp_login_id', models.AutoField(primary_key=True, serialize=False)),
                ('longin_time', models.DateTimeField(auto_now_add=True)),
                ('login_ip', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'emp_login_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('goods_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'goods_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('goods_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'goods_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialInfo',
            fields=[
                ('material_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'material_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('material_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('create_time', models.DateTimeField()),
                ('emp_id', models.IntegerField()),
                ('is_delete', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'material_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MerchantInfo',
            fields=[
                ('merchant_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=128)),
                ('sex', models.IntegerField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('phone_number', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'merchant_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('need_count', models.IntegerField()),
                ('unit', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'recipe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SimulatorData',
            fields=[
                ('simulator_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=64)),
                ('score', models.FloatField()),
                ('place', models.CharField(max_length=128)),
                ('sole_time', models.DateTimeField()),
                ('type_goods', models.IntegerField()),
                ('type_taste', models.IntegerField()),
                ('t_price', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('merchant_name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'simulator_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
                ('store_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'store_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StorePower',
            fields=[
                ('store_power_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'store_power',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StoreRole',
            fields=[
                ('store_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'store_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TasteType',
            fields=[
                ('taste_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('taste', models.CharField(max_length=128)),
                ('sales', models.IntegerField()),
                ('score', models.FloatField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'taste_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Relationship14',
            fields=[
                ('taste_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.TasteType')),
            ],
            options={
                'db_table': 'relationship_14',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Relationship23',
            fields=[
                ('admin_power', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.AdminPower')),
            ],
            options={
                'db_table': 'relationship_23',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Relationship7',
            fields=[
                ('store_power', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.StorePower')),
            ],
            options={
                'db_table': 'relationship_7',
                'managed': False,
            },
        ),
    ]
